- name: Set ignore errors
  set_fact:
    local_ignore_val: "{{ ignore_signal | string | lower }}"

- name: Run a task that might fail
  shell: "exit 1"
  ignore_errors: "{{ local_ignore_val == 'true' }}"
  any_errors_fatal: "{{ local_ignore_val == 'false' }}"
