During our recent debugging efforts, we discovered that LBaaS is causing significant delays in our file uploads. When we bypass LBaaS, the same files upload in around 30 seconds. However, when routed through LBaaS, the upload time extends to around 45 minutes.

We suspect there might be something in the LBaaS configuration that's blocking or slowing down the upload process. Could you help us by checking the LBaaS logs to identify any potential issues on your end?

Your assistance in resolving this would be greatly appreciated.
