- name: Debug the status field
  debug:
    var: http_responses.json.status

- name: Debug the HTTP status code
  debug:
    var: http_responses.status

- name: Debug the message field
  debug:
    var: http_responses.json.message
