Thanks, Maggie.

Based on the pure Python workflows, LBAAS is now working as expected after adjusting the receive window on the LBAAS side.

Ashwin, since these changes are related to the application from Spark, can we have someone from the dev team look into it?

We also need to handle the Spark workflows separately to increase the heap size and the maximum result size for Spark.
