- name: Get the hostname
  hosts: localhost
  tasks:
    - name: Get the hostname
      command: hostname
      register: hostname_result

    - name: Initialize retry count
      set_fact:
        retry_count: 0
        max_retries: 2

    - name: Loop to start sys_workflows and verify health
      include_tasks: start_sys_workflows_and_check_health.yml
      until: health_check.status == 200 and '"status":"ok"' in health_check.content
      retries: 2
      delay: 30
      ignore_errors: yes
      vars:
        version: "1.0"  # Replace with your version variable
        deploy_lane: "test"  # Replace with your deploy lane variable

    - name: Debug Start GCP SYS WORKFLOWS Version Output if failed
      debug:
        var: results
      when: health_check.status != 200 or '"status":"ok"' not in health_check.content

    - name: Start GCP SYS WORKFLOWS Version Failed
      fail:
        msg: "Startup script failed. Error: {{ results.stderr_lines | join('\n') }}"
      when: health_check.status != 200 or '"status":"ok"' not in health_check.content

    - name: Check if the health check succeeded
      fail:
        msg: "Health check failed after retries. Status: {{ health_check.status }}, Content: {{ health_check.content }}"
      when: health_check.status != 200 or '"status":"ok"' not in health_check.content
