Romil,

We have identified the root cause of the issue mentioned below and have submitted the necessary ARM ticket to gain access to the missing AD OU groups. Completing the full request will take a couple of hours.
