def get_credential(self, credentials_key):
    secret_path = f"{self.client['namespace']}/{credentials_key}"
    print(f"Attempting to retrieve secret from path: {secret_path}")
    response = self._send_request(f'secret/data/{secret_path}', method="GET", error_msg="Failed to retrieve credentials")
    return response['data']['data']
