# Stop script
stop_service() {
  if [[ -f ${GCP_PID} ]]; then
    /efs/dist/python/uWSGI/2.0.19.1/exec/3.7/bin/uwsgi --stop ${GCP_PID}
    sleep 90
    if [[ ! -f ${GCP_PID} && ! -f ${GCP_SOCK} ]]; then
      log "GCP ${ENV} process stopped"
    fi
  fi

  # Kill master PID if it exists
  GCP_MASTER_PID=$(ps -ef | grep -i jms-${ENV}UWSGI | grep $ENV | grep 'master' | awk '{print $2}')
  if [[ ! -z "$GCP_MASTER_PID" ]]; then
    kill -9 $GCP_MASTER_PID
    log "Killed gcp_sys_workflows Master PID [ $GCP_MASTER_PID ]!"
  fi

  # Kill any stale worker or emperor processes
  GCP_STALE_PID=$(ps -ef | grep -i jms-${ENV}UWSGI | grep $ENV | grep -E 'worker|emperor' | awk '$3 == 1 {print $2}')
  if [[ ! -z "$GCP_STALE_PID" ]]; then
    kill -9 $GCP_STALE_PID
    log "Killed stale gcp_sys_workflows worker/emperor PID [ $GCP_STALE_PID ]!"
  fi
}
