<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>File Upload</title>
</head>
<body>
    <h1>Upload a File</h1>
    <form id="uploadForm" action="http://your-server/upload" method="POST" enctype="multipart/form-data">
        <input type="file" name="file" id="fileInput">
        <input type="submit" value="Upload">
    </form>
    
    <p id="statusMessage"></p>
    <p id="timeMessage"></p>

    <script>
        document.getElementById('uploadForm').onsubmit = function(event) {
            event.preventDefault(); // Prevent the default form submission
            
            const formData = new FormData();
            const fileInput = document.getElementById('fileInput');
            formData.append('file', fileInput.files[0]);

            const xhr = new XMLHttpRequest();
            xhr.open('POST', this.action, true);
            
            xhr.onload = function() {
                const statusMessage = document.getElementById('statusMessage');
                const timeMessage = document.getElementById('timeMessage');
                
                if (xhr.status === 200) {
                    statusMessage.textContent = 'File uploaded successfully!';
                    const now = new Date();
                    timeMessage.textContent = 'Upload completed at: ' + now.toLocaleTimeString();
                } else {
                    statusMessage.textContent = 'File upload failed. Status: ' + xhr.status;
                    timeMessage.textContent = '';
                }
            };

            xhr.onerror = function() {
                const statusMessage = document.getElementById('statusMessage');
                statusMessage.textContent = 'An error occurred during the file upload.';
                timeMessage.textContent = '';
            };

            xhr.send(formData);
        };
    </script>
</body>
</html>
