Hi Savitha,

We are encountering a "permission denied" issue while retrieving credentials from the production Vault. We are able to log in to the Vault and successfully generate a token using the secret, but other API calls are failing due to permission denied errors.

Could you please help us resolve this as it is impacting our production environment?
