- name: Set email ID for UI reg and schema Evo based on branch name and Jenkins notification_email
  set_fact:
    ui_reg_email: "{{ notification_email if notification_email is defined and notification_email | length > 0 else 'dg.gcp_em_team@bofa.com' }}"
  when: branch_name is match("feature.*") or branch_name is match("bugfix.*")

- name: Set email ID for UI reg and schema Evo for develop and release branches or if notification_email is not provided
  set_fact:
    ui_reg_email: "{{ 'dg.gcp_em_team@bofa.com' if notification_email is not defined or notification_email | length == 0 else notification_email }}"
  when: branch_name == "develop" or branch_name is match("release.*")

- name: Debug ui_reg_email
  debug:
    msg: "UI Reg Email: {{ ui_reg_email }}"
  when: uas1_hosts|selectattr("name", "equalto", inventory_hostname)|list|length > 0
