We are looking to import the Horizon library and customize it based on our project needs. Our goal is to allow our users to leverage our custom library by simply importing it with something like @gcp, while only needing to pass a few parameters (ait, repo, and spk) for their respective repositories.

From what I understand, to achieve this, Horizon would need to add our repository URL into the global configurations. Could you please confirm if this is correct?

Additionally, I’d like to check if this approach is feasible. If so, could you please advise on the specific steps we would need to take on our end to facilitate this process?
