import timeit
import time

def long_running_task():
    result = []
    for i in range(1000000):
        s = str(i) + 'A' * 100
        result.append(s)
    result_str = ''.join(result)
    reversed_str = result_str[::-1]
    split_str = reversed_str.split('A')

# Start the timer
start_time = time.time()

# Timing the execution of a long-running task
execution_time = timeit.timeit('long_running_task()', globals=globals(), number=1)

# End the timer
end_time = time.time()

# Calculate the total duration
total_duration = end_time - start_time

# Print the results
print("Timing the execution of a long-running task:")
print(f"Timeit execution time: {execution_time} seconds")
print(f"Total duration: {total_duration} seconds")
