Hi Carlos,

The deployment failed during the schema evaluation step on the USA primary host (runs on only the primary host), which led to the build failure.

On both hosts, we installed the wheel package, and it went through successfully. However, on the primary UAS host, we run a few additional tasks, including UI regression and schema evaluation steps. This is where the issue occurred, resulting in a failure. Meanwhile, the secondary host sent a successful email notification as it completed the process without any issues.
