- name: Get the hostname
  command: hostname
  register: hostname_result

- name: Attempt to start sys_workflows and verify health
  block:
    - name: Start sys_workflows Version={{ version }}
      shell: "./start-gcp-sys-workflows.sh --env={{ deploy_lane }}"
      args:
        chdir: "{{ app_bin }}"
      register: results
      until: results.rc == 0
      retries: 3
      delay: 15

    - name: Wait for uwsgi to be up and running
      wait_for:
        port: "{{ uwsgi_port }}"
        host: "{{ hostname_result.stdout }}"
        delay: 5
        timeout: 30

    - name: Verify uwsgi service health
      uri:
        url: "http://{{ hostname_result.stdout }}:{{ uwsgi_port }}/health"
        return_content: yes
      register: health_check
      until: health_check.status == 200 and '"status":"ok"' in health_check.content
      retries: 5
      delay: 10
      ignore_errors: yes

    - name: Debug health check
      debug:
        msg:
          - "Health check status: {{ health_check.status }}"
          - "Health check content: {{ health_check.content }}"

  register: block_results
  until: block_results.results[-1].status == 200 and '"status":"ok"' in block_results.results[-1].content
  retries: 2
  delay: 30
  ignore_errors: no
