Subject: hVault Credential Keys Check Script

Team,

I’ve created a simple script to check hVault credential keys. The script retrieves the required namespace, role_id, and secret from the server's hvault.conf file. It then logs into hVault, retrieves a token, and fetches the specified client credentials.

You can find the script here: hVault Connection Check Script

Usage:

Activate the virtual environment:
bash
Copy code
source /gcp/uwsgi/venv/bin/activate
Run the script with the desired environment and key:
bash
Copy code
python hvault_connection_check.py --env dev1 --key GCP_CRED_L1D
