Hello Team,

We have identified a critical issue with our load balancer configuration that needs urgent attention. The IP addresses (30.134.234.41 and 30.134.234.76) assigned to our load balancer are pointing to two different hosts. This needs to be resolved as soon as possible due to the upcoming DR activity planned for next week.
