Thank you for your prompt action in resolving the issue with the DR load balancer IP.

I have a few follow-up questions to better understand the root cause and to prevent similar issues in the future:

Root Cause Analysis:
What was the root cause that led to a single IP being mapped to two different hosts?
Provisioning Details:
Did this issue occur during the initial provisioning of the load balancer, or was it mapped to dual hosts after provisioning?
Understanding these details will help us avoid any surprises in the future and ensure smoother operations.
