#!/bin/bash

# Files to compare
file_a="path/to/file_a"
file_b="path/to/file_b"

# Check if both files exist
if [[ ! -f "$file_a" || ! -f "$file_b" ]]; then
  echo "One or both files do not exist."
  exit 1
fi

# Compare the files and output the differences
diff_output=$(diff "$file_a" "$file_b")

if [[ -z "$diff_output" ]]; then
  echo "The files are identical."
else
  echo "The files differ:"
  echo "$diff_output"
fi
