#!/bin/bash

# Define the base paths
LOCAL_BASE_PATH="/gcp/dev1/apps/"
REMOTE_HOST="user@remote_host"
REMOTE_BASE_PATH="/gcp/dev1/apps/"

# Output file
DIFF_FILE="diff.txt"
> $DIFF_FILE  # Clear the diff file

# Function to gather repository names
gather_repos() {
    local BASE_PATH=$1
    ssh $REMOTE_HOST "find $BASE_PATH -maxdepth 1 -mindepth 1 -type d -exec basename {} \;" | sort
}

# Function to gather version names
gather_versions() {
    local REPO_PATH=$1
    ssh $REMOTE_HOST "find $REPO_PATH -maxdepth 1 -mindepth 1 -type d -exec basename {} \;" | sort
}

# Step 1: Compare Repositories
LOCAL_REPOS=$(find $LOCAL_BASE_PATH -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | sort)
REMOTE_REPOS=$(gather_repos $REMOTE_BASE_PATH)

# Iterate over each repository
for REPO in $LOCAL_REPOS; do
    if echo "$REMOTE_REPOS" | grep -q "^$REPO$"; then
        # Step 2: Compare Versions
        LOCAL_VERSIONS=$(find "$LOCAL_BASE_PATH/$REPO" -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | sort)
        REMOTE_VERSIONS=$(gather_versions "$REMOTE_BASE_PATH/$REPO")

        for VERSION in $LOCAL_VERSIONS; do
            if echo "$REMOTE_VERSIONS" | grep -q "^$VERSION$"; then
                # Step 3: Check venv existence
                LOCAL_VENV_PATH="$LOCAL_BASE_PATH/$REPO/$VERSION/venv"
                REMOTE_VENV_PATH="$REMOTE_BASE_PATH/$REPO/$VERSION/venv"

                if [ -d "$LOCAL_VENV_PATH" ] && ! ssh $REMOTE_HOST "[ -d $REMOTE_VENV_PATH ]"; then
                    echo "venv is MISSING in $REMOTE_VENV_PATH on remote host" | tee -a $DIFF_FILE
                fi
            else
                echo "Version $VERSION in repository $REPO is MISSING on remote host" | tee -a $DIFF_FILE
            fi
        done
    else
        echo "Repository $REPO is MISSING on remote host" | tee -a $DIFF_FILE
    fi
done

echo -e "\nCheck completed. Differences recorded in $DIFF_FILE"
