proxy_buffer_size 128k;
proxy_buffers 4 256k;
proxy_busy_buffers_size 256k;
    proxy_connect_timeout 120s;
    proxy_send_timeout 120s;
    proxy_read_timeout 120s;

    We haven't received a response from the vault team yet. We'll follow up again today, but please note that this might be an intermittent issue. It won't cause problems all the time. Please try submitting again, and let us know if you're still encountering the issue.
