import timeit
import time
import numpy as np

def long_running_task():
    size = 500
    matrix_a = np.random.rand(size, size)
    matrix_b = np.random.rand(size, size)
    for _ in range(100):
        np.dot(matrix_a, matrix_b)

# Start the timer
start_time = time.time()

# Timing the execution of a long-running task
execution_time = timeit.timeit('long_running_task()', globals=globals(), number=10)

# End the timer
end_time = time.time()

# Calculate the total duration
total_duration = end_time - start_time

# Print the results
print("Timing the execution of a long-running task:")
print(f"Timeit execution time: {execution_time} seconds")
print(f"Total duration: {total_duration} seconds")
