Hi Nathan,

The non-prod tester has TCP timestamps enabled as well. Could we set up a call to discuss possible workaround solutions? Please let me know if 10:30 CT works for you.

For your information, I’ve already tried switching the production LBaaS (test) to the non-prod pool, but I am still experiencing the same delays.
