Additionally, it may not be ideal to modify individual user settings. We need a solution that works without requiring changes on the client side, as the clients are set to default configurations and cannot be overridden
