"I have created a playbook to deploy nginx_ui, nginx, and gcp_sys_workflows.ini files for dev1. Please review the changes, add the remaining lane ports and hostnames to the system_configs.yml, and test it."
