- name: Check for code misuse keywords
  block:
    - name: Call code misuse endpoint
      uri:
        url: "{{ nginx.protocol }}://{{ host.name }}:{{ nginx.port }}/platform/validator/code_misuse"
        method: POST
        body_format: json
        body:
          repo_name: "{{ repo }}"
          spk: "{{ spk }}"
          branch_name: "{{ branch_name }}"
          repo_version: "{{ normalized_version }}"
          gcp_version: "{{ gcp_version }}"
        return_content: yes
      register: http_responses
      failed_when:
        - http_responses.json.status != "OK"   # Fails if the status in the response JSON is not "OK"
        - "'FAILED' in http_responses.json.message"  # Fails if the message indicates failure
        - http_responses.status != 200  # Additional check: if the actual HTTP status is not 200
  rescue:
    - name: Display failure and stop execution
      fail:
        msg: "GCP Code misuse detected. Error: {{ http_responses.json.message }}"

