- name: Collect ATF Tests Block
  block:
    - name: Set ignore errors
      set_fact:
        local_ignore_val: "{{ local_ignore_reg | default('false') }}"

    - name: Set package name
      set_fact:
        local_package_name: "{{ 'gcp_kernel' if repo == 'gcp' else repo }}"

    - name: Collect ATF Tests
      shell: |
        source venv/bin/activate
        python -m gcp_kernel.testing.atf.collector -r {{ local_package_name }} -v {{ normalized_version }} -e {{ deploy_lane }} {% if gcp_version is version_compare('4.30', '>=') %} -b {{ branch_name }} {% endif %}
      args:
        chdir: "{{ deployment_root }}"
      register: results
      ignore_errors: "{{ local_ignore_val }}"
