#!/bin/bash

# Define the local path and the remote host with path
LOCAL_PATH="/appdat/cluster/prod/"
REMOTE_HOST="user@remote_host"
REMOTE_PATH="/appdat/cluster/prod/"

# Get the list of directories locally
DIRS_LOCAL=$(find $LOCAL_PATH -maxdepth 1 -mindepth 1 -type d | sort)

# Get the list of directories from the remote host
DIRS_REMOTE=$(ssh $REMOTE_HOST "find $REMOTE_PATH -maxdepth 1 -mindepth 1 -type d | sort")

# Compare the directories between the local host and the remote host
echo "Comparing directories between local host and $REMOTE_HOST:"
diff <(echo "$DIRS_LOCAL") <(echo "$DIRS_REMOTE")

# Function to check venv existence
check_venv() {
    local DIR=$1
    [[ -d $DIR/venv ]] && echo "venv exists in $DIR" || echo "venv does NOT exist in $DIR"
}

# Check venv existence in each local directory
echo -e "\nChecking for venv existence on local host:"
for DIR in $DIRS_LOCAL; do
    check_venv $DIR
done

# Check venv existence in each remote directory
echo -e "\nChecking for venv existence on $REMOTE_HOST:"
for DIR in $DIRS_REMOTE; do
    ssh $REMOTE_HOST "[[ -d $DIR/venv ]] && echo 'venv exists in $DIR' || echo 'venv does NOT exist in $DIR'"
done
