proxy_buffer_size 128k;
proxy_buffers 4 256k;
proxy_busy_buffers_size 256k;
    proxy_connect_timeout 120s;
    proxy_send_timeout 120s;
    proxy_read_timeout 120s;

    Sure, if patching or deployment occurs, the entire service will go down. I want to test some changes in NGINX, which is why I need help replicating this issue in ILEs.
