Hi Nathan,

As you're aware, installing Wireshark requires multiple approvals and cannot be completed in a single day. Additionally, do we really need Red Hat here? Since it’s an OS, I don’t believe it's contributing to the delay. Perhaps we can seek assistance from the Unix team to capture the TCP connections without involving Avi?
