Masthan,

There is no limit set for file uploads. Based on the time ranges below, we will adjust the NGINX timeout settings to prevent 500 errors.

Maggie,

Are we calculating only the file upload time or including workflow execution in Priya’s case? Before applying the changes, it took me 40 minutes, but afterward, it only took 1 minute to upload the file
