- name: Deploy and Check GCP Service
  hosts: my_hosts
  gather_facts: yes
  vars_files:
    - main.yml

  tasks:
    - name: Initialize check variables
      set_fact:
        health_check_retries: 5
        health_check_delay: 10

    - name: Start sys_workflows Version={{ version }}
      shell: "./start-gcp-sys-workflows.sh --env={{ deploy_lane }}"
      args:
        chdir: "{{ app_bin }}"
      register: results
      until: results.rc == 0
      retries: 3
      delay: 15

    - name: Debug final health check url
      debug:
        msg:
          - "Final health check url - https://{{ ansible_default_ipv4.address }}:{{ port }}"

    - name: Verify uwsgi service health
      block:
        - name: Perform initial health check
          uri:
            url: "https://{{ ansible_default_ipv4.address }}:{{ port }}/health"
            return_content: yes
          register: health_check
          retries: "{{ health_check_retries }}"
          delay: "{{ health_check_delay }}"
          ignore_errors: yes

        - name: Debug initial health check
          debug:
            msg:
              - "Health check status: {{ health_check.status }}"
              - "Health check content: {{ health_check.content }}"

        - name: Restart sys_workflows using script if health check fails
          shell: "./start-gcp-sys-workflows.sh --env={{ deploy_lane }}"
          args:
            chdir: "{{ app_bin }}"
          register: restart_results
          when: health_check.status != 200

        - name: Perform health check after restart
          uri:
            url: "https://{{ ansible_default_ipv4.address }}:{{ port }}/health"
            return_content: yes
          register: health_check
          retries: "{{ health_check_retries }}"
          delay: "{{ health_check_delay }}"
          when: health_check.status != 200
          ignore_errors: yes

        - name: Debug health check after restart
          debug:
            msg:
              - "Health check status after restart: {{ health_check.status }}"
              - "Health check content after restart: {{ health_check.content }}"
      when: health_check.status != 200

    - name: Fail if final health check fails
      fail:
        msg: "uwsgi health check failed after retries: {{ health_check.content }}"
      when: health_check.status != 200
